name: Sample Maven-Example
on:
  push:
  pull_request:
    types: [opened, reopened]
  
jobs:
  CI:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest] #, windows-latest]
        java-version: [1.8, 1.13]
      fail-fast: true
    env:
      CI: true

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setting Java ${{ matrix.java-version }} on ${{ matrix.os }}
        uses: actions/setup-java@v1  
        with:
          java-version: ${{ matrix.java-version }}
      - name: Caching Maven Packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          repository-keys: ${{ runner.os }}-m2
      - name: Build
        run: mvn -B package
      - name: Upload Artifacts
        uses: actions/upload-artifact@v1
        with:
          name: mvn-artifact
          path: target/java-tomcat-maven-example.war
      - name: Notify Slack
        run: |
          curl -X POST --data-urlencode "payload={\"channel\": \"#cje-testing\", \"username\": \"webhookbot\", \"text\": \"The status of the job ${{ github.event_name }}.\", \"icon_emoji\": \":github:\"}" ${{ secrets.SLACK_WEBHOOK }}
